export enum RatioType {
  gain = 'gain',
  vitesse = 'vitesse',
  ange = 'ange',
}

export const origworld = {
  name: 'Tunisian Capitalist',
  logo: 'icones/logo-tunisian-capitalist.png',
  money: 0,
  score: 0,
  totalangels: 0,
  activeangels: 0,
  angelbonus: 2,
  lastupdate: 0,
  products: [
    {
      id: 1,
      name: 'Cookies',
      logo: 'icones/cookies.png',
      cout: 10,
      croissance: 1.07,
      revenu: 1,
      vitesse: 1000,
      quantite: 1,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Four du quartier',
          logo: 'icones/cookies.png',
          seuil: 25,
          idcible: 1,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Livraisons express',
          logo: 'icones/cookies.png',
          seuil: 50,
          idcible: 1,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Cookies signature',
          logo: 'icones/cookies.png',
          seuil: 100,
          idcible: 1,
          ratio: 3,
          typeratio: RatioType.gain,
          unlocked: false,
        },
      ],
    },
    {
      id: 2,
      name: 'Fricassé',
      logo: 'icones/fricasse.png',
      cout: 100,
      croissance: 1.09,
      revenu: 12,
      vitesse: 3000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Harissa maison',
          logo: 'icones/fricasse.png',
          seuil: 25,
          idcible: 2,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Service rapide',
          logo: 'icones/fricasse.png',
          seuil: 50,
          idcible: 2,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Fricassé royal',
          logo: 'icones/fricasse.png',
          seuil: 100,
          idcible: 2,
          ratio: 3,
          typeratio: RatioType.gain,
          unlocked: false,
        },
      ],
    },
    {
      id: 3,
      name: 'Makloub',
      logo: 'icones/makloub.png',
      cout: 1000,
      croissance: 1.11,
      revenu: 150,
      vitesse: 6000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Galette artisanale',
          logo: 'icones/makloub.png',
          seuil: 25,
          idcible: 3,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Plaque chauffante',
          logo: 'icones/makloub.png',
          seuil: 50,
          idcible: 3,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Makloub du chef',
          logo: 'icones/makloub.png',
          seuil: 100,
          idcible: 3,
          ratio: 3,
          typeratio: RatioType.gain,
          unlocked: false,
        },
      ],
    },
    {
      id: 4,
      name: 'Mechwi',
      logo: 'icones/mechwi.png',
      cout: 10000,
      croissance: 1.13,
      revenu: 1800,
      vitesse: 12000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Charbon d’olivier',
          logo: 'icones/mechwi.png',
          seuil: 25,
          idcible: 4,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Grillade express',
          logo: 'icones/mechwi.png',
          seuil: 50,
          idcible: 4,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Mechwi de fête',
          logo: 'icones/mechwi.png',
          seuil: 100,
          idcible: 4,
          ratio: 3,
          typeratio: RatioType.gain,
          unlocked: false,
        },
      ],
    },
    {
      id: 5,
      name: 'Zgougou',
      logo: 'icones/zgougou.png',
      cout: 100000,
      croissance: 1.15,
      revenu: 22000,
      vitesse: 24000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Pignons sélectionnés',
          logo: 'icones/zgougou.png',
          seuil: 25,
          idcible: 5,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Préparation rapide',
          logo: 'icones/zgougou.png',
          seuil: 50,
          idcible: 5,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Assida de prestige',
          logo: 'icones/zgougou.png',
          seuil: 100,
          idcible: 5,
          ratio: 3,
          typeratio: RatioType.gain,
          unlocked: false,
        },
      ],
    },
    {
      id: 6,
      name: 'Couscous',
      logo: 'icones/couscous.png',
      cout: 1000000,
      croissance: 1.17,
      revenu: 280000,
      vitesse: 45000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Semoule premium',
          logo: 'icones/couscous.png',
          seuil: 25,
          idcible: 6,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Couscoussier géant',
          logo: 'icones/couscous.png',
          seuil: 50,
          idcible: 6,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Couscous familial',
          logo: 'icones/couscous.png',
          seuil: 100,
          idcible: 6,
          ratio: 3,
          typeratio: RatioType.gain,
          unlocked: false,
        },
      ],
    },
  ],
  allunlocks: [
    {
      name: 'Souk en effervescence',
      logo: 'icones/logo-tunisian-capitalist.png',
      seuil: 10,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Festival gastronomique tunisien',
      logo: 'icones/logo-tunisian-capitalist.png',
      seuil: 25,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Fierté culinaire nationale',
      logo: 'icones/logo-tunisian-capitalist.png',
      seuil: 50,
      idcible: 0,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
  upgrades: [
    {
      name: 'Four traditionnel rénové',
      logo: 'icones/cookies.png',
      seuil: 500,
      idcible: 1,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Huile d’olive première pression',
      logo: 'icones/fricasse.png',
      seuil: 2000,
      idcible: 2,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Plaque de cuisson professionnelle',
      logo: 'icones/makloub.png',
      seuil: 10000,
      idcible: 3,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Rôtissoire artisanale',
      logo: 'icones/mechwi.png',
      seuil: 50000,
      idcible: 4,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Pignons de qualité',
      logo: 'icones/zgougou.png',
      seuil: 200000,
      idcible: 5,
      ratio: 4,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Couscoussier professionnel',
      logo: 'icones/couscous.png',
      seuil: 1000000,
      idcible: 6,
      ratio: 4,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Recette secrète des cookies',
      logo: 'icones/cookies.png',
      seuil: 5000,
      idcible: 1,
      ratio: 5,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Harissa extra forte',
      logo: 'icones/fricasse.png',
      seuil: 20000,
      idcible: 2,
      ratio: 5,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Viande marinée du Makloub',
      logo: 'icones/makloub.png',
      seuil: 100000,
      idcible: 3,
      ratio: 5,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Marinade spéciale Mechwi',
      logo: 'icones/mechwi.png',
      seuil: 500000,
      idcible: 4,
      ratio: 5,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
  angelupgrades: [
    {
      name: 'Bénédiction de Sidi Bou Saïd',
      logo: 'icones/angel.png',
      seuil: 10,
      idcible: 0,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Festival des saveurs',
      logo: 'icones/angel.png',
      seuil: 25,
      idcible: 0,
      ratio: 5,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Baraka céleste',
      logo: 'icones/angel.png',
      seuil: 100,
      idcible: -1,
      ratio: 2,
      typeratio: RatioType.ange,
      unlocked: false,
    },
  ],
  managers: [
    {
      name: 'La pâtissière du quartier',
      logo: 'icones/manager-cookies.png',
      seuil: 1000,
      idcible: 1,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Ammar le fricassier',
      logo: 'icones/manager-fricasse.png',
      seuil: 10000,
      idcible: 2,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Chef Makloub',
      logo: 'icones/manager-makloub.png',
      seuil: 100000,
      idcible: 3,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Maître du Mechwi',
      logo: 'icones/manager-mechwi.png',
      seuil: 1000000,
      idcible: 4,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'La spécialiste du Zgougou',
      logo: 'icones/manager-zgougou.png',
      seuil: 10000000,
      idcible: 5,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Si Couscous',
      logo: 'icones/manager-couscous.png',
      seuil: 100000000,
      idcible: 6,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
};
